"""Add search_vector column to products table

Revision ID: 7719b63ddb34
Revises:
Create Date: 2025-03-13 11:29:16.960852

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7719b63ddb34"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True)
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=100),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.TEXT(),
            type_=sa.String(length=200),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.String(length=200),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )
        batch_op.drop_column("search_vector")

    # ### end Alembic commands ###
